### ISSUE TITLE
add_resource_path not handling non-existing inst/app/www path

### ISSUE THREAD

**Issue by fvitalini** [ThinkR-open/golem#395]
I have noticed an issue when running R CMD Check with empty/non-existing `inst/app/www` path (R CMD Check removes empty directories).

The function `golem::add_resources_path()` does not handle such a case and `shiny::addResourcePath` fails while normalizing the path which is an empty string.

To reproduce the issue:
1) create a new progect with `golem` from template
2) run `golem::remove_favicon()`
3) run `devtools::check(document = FALSE)`

**Comment by ColinFay** [comment]
Thanks for reporting @fvitalini! 

Can you please share what version of golem you are using?

Thanks :)

**Comment by fvitalini** [comment]
Sure, here is my `session_info()`. Btw I have installed `golem` from github yesterday.
```
> session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Ubuntu 18.04.4 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Rome                 
 date     2020-03-10                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────
 ! package     * version    date       lib source                            
   assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                    
   attempt       0.3.0      2019-04-08 [1] CRAN (R 3.6.2)                    
 P babyMeasure * 0.0.0.9000 2020-03-10 [?] local                             
   backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.2)                    
   callr         3.4.2      2020-02-12 [1] CRAN (R 3.6.3)                    
   cli           2.0.2      2020-02-28 [1] CRAN (R 3.6.3)                    
   config        0.3        2018-03-27 [1] CRAN (R 3.6.3)                    
   crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                    
   desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                    
   devtools    * 2.2.1      2019-09-24 [1] CRAN (R 3.6.2)                    
   digest        0.6.25     2020-02-23 [1] CRAN (R 3.6.3)                    
   dockerfiler   0.1.3      2019-03-19 [1] CRAN (R 3.6.2)                    
   DT            0.11       2019-12-19 [1] CRAN (R 3.6.2)                    
   ellipsis      0.3.0      2019-09-20 [1] CRAN (R 3.6.2)                    
   fansi         0.4.1      2020-01-08 [1] CRAN (R 3.6.2)                    
   fastmap       1.0.1      2019-10-08 [1] CRAN (R 3.6.2)                    
   fs            1.3.2      2020-03-05 [1] CRAN (R 3.6.3)                    
   glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                    
   golem       * 0.2.1      2020-03-09 [1] Github (Thinkr-open/golem@bf9d041)
   htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.2)                    
   htmlwidgets   1.5.1      2019-10-08 [1] CRAN (R 3.6.2)                    
   httpuv        1.5.2.9000 2020-02-04 [1] Github (rstudio/httpuv@4164605)   
   jsonlite      1.6.1      2020-02-02 [1] CRAN (R 3.6.2)                    
   later         1.0.0      2019-10-04 [1] CRAN (R 3.6.2)                    
   magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.0)                    
   memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                    
   mime          0.9        2020-02-04 [1] CRAN (R 3.6.3)                    
   packrat       0.5.0      2018-11-14 [1] CRAN (R 3.6.2)                    
   pkgbuild      1.0.6      2019-10-09 [1] CRAN (R 3.6.2)                    
   pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                    
   prettyunits   1.1.1      2020-01-24 [1] CRAN (R 3.6.2)                    
   processx      3.4.2      2020-02-09 [1] CRAN (R 3.6.3)                    
   promises      1.1.0.9000 2020-02-04 [1] Github (rstudio/promises@627dfc6) 
   ps            1.3.2      2020-02-13 [1] CRAN (R 3.6.3)                    
   purrr         0.3.3      2019-10-18 [1] CRAN (R 3.6.2)                    
   R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.2)                    
   Rcpp          1.0.3      2019-11-08 [1] CRAN (R 3.6.2)                    
   remotes       2.1.1      2020-02-15 [1] CRAN (R 3.6.3)                    
   rlang         0.4.5      2020-03-01 [1] CRAN (R 3.6.3)                    
   roxygen2      7.0.2      2019-12-02 [1] CRAN (R 3.6.2)                    
   rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.6.0)                    
   rstudioapi    0.11       2020-02-07 [1] CRAN (R 3.6.3)                    
   sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                    
   shiny       * 1.4.0      2019-10-10 [1] CRAN (R 3.6.2)                    
   stringi       1.4.6      2020-02-17 [1] CRAN (R 3.6.2)                    
   stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                    
   testthat    * 2.3.2      2020-03-02 [1] CRAN (R 3.6.3)                    
   usethis     * 1.5.1      2019-07-04 [1] CRAN (R 3.6.0)                    
   withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.0)                    
   xml2          1.2.2      2019-08-09 [1] CRAN (R 3.6.1)                    
   xtable        1.8-4      2019-04-21 [1] CRAN (R 3.6.0)                    
   yaml          2.2.1      2020-02-01 [1] CRAN (R 3.6.3)                    
```

**Comment by ColinFay** [comment]
Thanks a lot. I was asking because that was a bug in the last version and I thought it had been handled in the new version. 

I'll investigate on it, thanks for sharing !

**Comment by ColinFay** [comment]
The current `golem::add_resources_path` tests that the folder is empty or not (since v0.2.0), so even if `www` is empty, the application shouldn't fail to launch 🤔

I don't think `add_resources_path` is directly tested when running `devtools::check` but you might be experiencing the issue described in https://github.com/ThinkR-open/golem/issues/401 ?

**Comment by fvitalini** [comment]
@ColinFay  I have the issue by running R CMD Check both in Rstudio and via `devtools::check(document = FALSE)` . What fails is the recommended test:

```
── 2. Failure: app launches (@test-golem-recommended.R#29)  ────
x$is_alive() isn't true.
```

However, running the test manually in the console

```
    x <- processx::process$new(
      "R", 
      c(
        "-e", 
        "pkgload::load_all(here::here());run_app()"
      )
    )
    Sys.sleep(5)
    expect_true(x$is_alive())
    x$kill()
```

Is fine.

**Comment by ColinFay** [comment]
Thanks for the feedaback. 

That's indeed a bug in the golem test, we are working on it currently in #410. 
I'll ping you back here when it's corrected so that you can check that everything is working again :)

**Comment by fvitalini** [comment]
Thanks!

**Comment by ColinFay** [comment]
Hey, 

This bug should have been corrected via #435. 

Can you confirm by reinstalling the current version of `{golem}` from GitHub, then run: 

``` r
packageVersion("golem") == "0.2.1.9010"
unlink("tests/testthat/test-golem-recommended.R")
golem::use_recommended_tests()
devtools::test()
devtools::check()
``` 

Thanks

**Comment by fvitalini** [comment]
Hi @ColinFay ,

unfortunately I still see the error:

```
── Test failures ───────────────────────────────────────────────────────────────────────────────────────────────────────────────── testthat ────

> library(testthat)
> library(testGolem)
> 
> test_check("testGolem")
── 1. Error: app ui (@test-golem-recommended.R#2)  ─────────────────────────────────────────────────────────────────────────────────────────────
Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'www'; `directoryPath` = ''
Backtrace:
  1. testGolem:::app_ui()
  4. testGolem:::golem_add_external_resources()
  5. golem::add_resource_path("www", app_sys("app/www"))
  6. shiny::addResourcePath(prefix, directoryPath)
  7. base::tryCatch(...)
  8. base:::tryCatchList(expr, classes, parentenv, handlers)
  9. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 10. value[[3L]](cond)

══ testthat results  ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
[ OK: 1 | SKIPPED: 1 | WARNINGS: 0 | FAILED: 1 ]
1. Error: app ui (@test-golem-recommended.R#2) 

Error: testthat unit tests failed
Execution halted

1 error x | 0 warnings ✓ | 0 notes ✓
```

Here is my sessionInfo()

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=it_IT.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=it_IT.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=it_IT.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=it_IT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] testGolem_0.0.0.9000 testthat_2.3.2      

loaded via a namespace (and not attached):
 [1] spelling_2.1        xfun_0.13           remotes_2.1.1       purrr_0.3.4         rcmdcheck_1.3.3     htmltools_0.4.0     usethis_1.6.1      
 [8] yaml_2.2.1          rlang_0.4.5         pkgbuild_1.0.7      later_1.0.0         glue_1.4.0          withr_2.2.0         xopen_1.0.0        
[15] hunspell_3.0        sessioninfo_1.1.1   stringr_1.4.0       devtools_2.2.2      htmlwidgets_1.5.1   memoise_1.1.0       knitr_1.28         
[22] callr_3.4.3         fastmap_1.0.1       golem_0.2.1.9010    httpuv_1.5.2.9000   ps_1.3.2            fansi_0.4.1         Rcpp_1.0.4.6       
[29] xtable_1.8-4        promises_1.1.0.9000 backports_1.1.6     DT_0.12             desc_1.2.0          pkgload_1.0.2       jsonlite_1.6.1     
[36] config_0.3          mime_0.9            fs_1.4.1            packrat_0.5.0       digest_0.6.25       stringi_1.4.6       processx_3.4.2     
[43] shiny_1.4.0.2       rprojroot_1.3-2     here_0.1            cli_2.0.2           tools_3.6.3         dockerfiler_0.1.3   magrittr_1.5       
[50] crayon_1.3.4        ellipsis_0.3.0      xml2_1.3.2          prettyunits_1.1.1   attempt_0.3.0       assertthat_0.2.1    roxygen2_7.1.0     
[57] rstudioapi_0.11     R6_2.4.1            compiler_3.6.3     
```

Hope this helps.

**Comment by ColinFay** [comment]
Can you share the content of you golem_add_external_resources() function please?

**Comment by ColinFay** [comment]
That part about the resource path should be skipped if the folder is empty 🤔

Any chance you can share the project on GitHub so I can have a look at the full code? 

Thanks

**Comment by fvitalini** [comment]
Yes, I just added the test project I used to reproduce the error here https://github.com/fvitalini/testGolem

**Comment by ColinFay** [comment]
Thanks for taking the time to share this. Will have a look and come back at you 💪💪

**Comment by ColinFay** [comment]
Hey @fvitalini, 

Thank you very much, this should be fixed via #438. 

Can you install the current dev version (`0.2.1.9020`) and confirm?

```
remotes::install_github("thinkr-open/golem", ref = "dev")
packageVersion("golem") == "0.2.1.9020"
unlink("tests/testthat/test-golem-recommended.R")
golem::use_recommended_tests()
devtools::test()
devtools::check()
```

**Comment by fvitalini** [comment]
@ColinFay  with version `0.2.1.9020` the issue does not occur anymore. Thanks for looking into this!

**Comment by ColinFay** [comment]
Perfect, thanks !

**Comment by fvitalini** [comment]
@ColinFay I am running int this issue again.

A reproducible example can be found at https://github.com/fvitalini/testGolemShinyProdMinimal

It is a simple project initialized with golem, where the only thing I did was `golem::remove_favicon()`
This causes the `inst/app/www` folder to be empty and therefore not committed to git. If you fork the project, the path is not available and running the application with

`testGolemShinyProdMinimal::run_app()`

causes the app to crash 

![image](https://user-images.githubusercontent.com/13469315/100218086-8b6d9c80-2f14-11eb-9049-cd9b6b4c23be.png)

Here is my `sessionInfo()`

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=it_IT.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=it_IT.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=it_IT.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=it_IT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.5.0                          testGolemShinyProdMinimal_0.0.0.9000 testthat_2.3.2                      
[4] devtools_2.3.2                       usethis_1.6.3                       

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        compiler_4.0.3    later_1.1.0.1     prettyunits_1.1.1 remotes_2.2.0     tools_4.0.3       digest_0.6.27    
 [8] pkgbuild_1.1.0    pkgload_1.1.0     jsonlite_1.7.1    memoise_1.1.0     rlang_0.4.8       cli_2.1.0         rstudioapi_0.13  
[15] yaml_2.2.1        golem_0.2.1       xfun_0.18         fastmap_1.0.1     xml2_1.3.2        knitr_1.30        stringr_1.4.0    
[22] roxygen2_7.1.1    withr_2.3.0       desc_1.2.0        fs_1.5.0          attempt_0.3.1     rprojroot_1.3-2   glue_1.4.2       
[29] R6_2.5.0          processx_3.4.4    fansi_0.4.1       sessioninfo_1.1.1 purrr_0.3.4       dockerfiler_0.1.3 callr_3.5.1      
[36] magrittr_1.5      backports_1.1.10  ps_1.4.0          promises_1.1.1    ellipsis_0.3.1    htmltools_0.5.0   rsconnect_0.8.16 
[43] assertthat_0.2.1  mime_0.9          xtable_1.8-4      httpuv_1.5.4      config_0.3        stringi_1.5.3     crayon_1.3.4    
```

**Comment by ColinFay** [comment]
Hey ! 

According to your session info you're using the CRAN version of ˋ{golem}ˋ

Can you try with the current version from GitHub (0.3.0) ?

If ever this solves the issue, one way to be sure to have this one used in your app is:

- install golem from GitHub 
- run usethis::use_dev_package("golem")
- run usethis::use_latest_dependencies()

This should put in your DESCRIPTION the strict version

**Comment by fvitalini** [comment]
Yes, with the dev version the issue does not occur anymore. Thanks!
