### ISSUE TITLE
config.yml not found in current working directory

### ISSUE THREAD

**Issue by seanhardison1** [ThinkR-open/golem#420]
Hi,

I can't seem to get around this error when I build and then attempt to run my app using `run_app()`:

```
Warning: Error in get: Config file config.yml not found in current working directory or parent directories
```

The file golem-config.yml is currently in`inst/`, and the error doesn't stop the package from building nor the app from initializing. I'm just greeted with the error upon trying to use the app once it loads.

Any ideas why this might be happening?

The package in question can be found [here](https://github.com/seanhardison1/vcrshiny)

**Comment by VincentGuyader** [comment]
Hi, 

this one was hard to find :)

I spend much time inside ggplotly :p , it's not a golem issue, and not a ggplotly issue

in your code you use  `get(paste(variable))`

put instead :  

```
p <- ggplot2::ggplot(data = df) +
      ggplot2::geom_line(ggplot2::aes(x = datetime, y = base::get(paste(variable)),
                    color = station)) +
      ggplot2::theme_bw() +
      ggplot2::ylab(ylabel)
```


Regards 

(and dont use `return` inside `reactive`)

**Comment by ColinFay** [comment]
In your application, `get` is getting overriden by `config::get` which is exported in `get_golem_config()`.

I'm assigning this to myself to switch to explicit namespacing inside `get_golem_config` instead of importing.

**Comment by seanhardison1** [comment]
Wow, thank you!! Great catch.

**Comment by ColinFay** [comment]
FWIW, it has been corrected in https://github.com/ThinkR-open/golem/pull/432

**Comment by gacolitti** [comment]
How is it that importing `config::get()` in `get_golem_config()` exports a `my.golem.package::get()` function? 

Also, I'm using {golem} 0.3.2 and I still see a namespace conflict. If I remove `@importFrom config get` from `get_golem_config()`, then there is no namespacing conflict.
